/**
 * Discover installed question-module packages and generate the registry composition.
 *
 * The engine is content-agnostic: it ships with no questions. A question-module package advertises
 * itself with the keyword "philosoph-question-modules" in its package.json and exports
 * `MODULES: readonly QuestionModule[]`. This script scans node_modules for those packages and
 * writes a generated file — with *static* imports, so tsc and any bundler stay happy — that each
 * Node consumer (the API server, the reports CLI) composes into a registry.
 *
 * With none installed, the generated list is empty: the app runs, there are simply no questions
 * until a module package is added (`yarn add <a-question-module-package>` then re-run this).
 *
 * Runs automatically before `dev` / `start` / `build` / `typecheck` / `report`; also standalone as
 * `yarn modules:sync`.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MARKER = "philosoph-question-modules";

/** Node consumers that compose the registry; each gets an identical generated file. */
const TARGETS = ["api/src/generated/installed-modules.ts", "reports/src/generated/installed-modules.ts"];

/** Every installed package (top-level, hoisted) whose package.json carries the marker keyword. */
function findModulePackages() {
  const nodeModules = path.join(ROOT, "node_modules");
  if (!fs.existsSync(nodeModules)) return [];

  // node_modules holds either bare packages or `@scope/` directories of packages.
  const dirs = [];
  for (const entry of fs.readdirSync(nodeModules)) {
    if (entry.startsWith(".")) continue;
    const full = path.join(nodeModules, entry);
    if (entry.startsWith("@")) {
      if (!fs.statSync(full).isDirectory()) continue;
      for (const sub of fs.readdirSync(full)) dirs.push(path.join(full, sub));
    } else {
      dirs.push(full);
    }
  }

  const names = new Set();
  for (const dir of dirs) {
    const pkgPath = path.join(dir, "package.json");
    if (!fs.existsSync(pkgPath)) continue;
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
      if (Array.isArray(pkg.keywords) && pkg.keywords.includes(MARKER) && pkg.name) names.add(pkg.name);
    } catch {
      /* unreadable/!json — skip */
    }
  }
  return [...names].sort();
}

function render(names) {
  const imports = names.map((n, i) => `import { MODULES as p${i} } from ${JSON.stringify(n)};`);
  const spread = names.map((_, i) => `...p${i}`).join(", ");
  return `${[
    `// AUTO-GENERATED by \`yarn modules:sync\` — do not edit by hand.`,
    `// Question-module packages found in node_modules (keyword "${MARKER}").`,
    `// Empty when none are installed — the engine is content-agnostic.`,
    ``,
    `import type { QuestionModule } from "@philosoph/module-api";`,
    ...imports,
    ``,
    `export const installedModules: readonly QuestionModule[] = [${spread}];`,
  ].join("\n")}\n`;
}

const names = findModulePackages();
const content = render(names);
for (const rel of TARGETS) {
  const out = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, content);
}
console.log(
  `[modules:sync] ${names.length} question-module package(s)${names.length ? `: ${names.join(", ")}` : " — content-agnostic, no questions until one is installed"}`,
);
